server:
  port: 8080

actions:
  qrUrlTemplate: "http://localhost:8081/#/{actionId}"

jwt:
  secret: "SECRET"

facebook:
  secret: "SECRET"

recommender:
  unigramConsidered: true

metricsReport:
  to: admin@example.om
  schedule: "0 0 2 * * *" # Every night at 2 AM